Algoritmo "semnome"

Var

       n1, n2, n3, conta, soma : real

Inicio
        escreval("Sistema de notas de provas!")

        escreva("Digite a primeira nota: ")
        leia(n1)

        escreva("Digite a segunda nota: ")
        leia(n2)

        escreva("Digite a terceira nota: ")
        leia(n3)
        
        conta <- n1 *1 + n2 * 2 + n3 *3
        soma <- conta + 1 + 2 +3
        
        escreva("A Média do aluno(a) foi de, ", soma :1:1 )
        

        


Fimalgoritmo