Algoritmo "semnome"


Var

   num1, soma : inteiro


Inicio
         escreva("Digite um número para saber se ele é Par ou Ímpar: ")
         leia(num1)
         
         soma <- num1  % 2
         
         se (soma = 0) entao
            escreva("O número ", num1, " é par")
            
         senão
              escreva("O número ", num1, " é Ímpar")
              
         fimse
         
         


Fimalgoritmo