Algoritmo "semnome"

Var
        temperatura : real


Inicio
        escreva("Qual o valor da temperatura ambiente: ")
        leia(temperatura)
        
        se (temperatura >= 30) entao
           escreva("Está muito MUITO quente :p")
        senao
             se (temperatura >= 25)entao
              escreva("Está quente")
        senao
             escreva("está agradavel")
             
            fimse

        fimse

Fimalgoritmo